### ISSUE TITLE
Working with abstract types like `blob`

### ISSUE THREAD

**Issue by phated** [BuckleTypes/bs-fetch#12]
I see that most of the Body results are represented by abstract types (if I have that terminology correct?) like `blob`, `arrayBuffer`, etc.  The exceptions being `json` using `Js.Json.t` and `text` using `string`.  Every example I have found is only using those 2 methods but I don't quite understand how someone would work with the abstract types.  Any advice or links would be greatly appreciated!

**Comment by glennsl** [comment]
Your terminology is a bit off. `Js.Json.t` is also an abstract type, which just means it has no "structure" to it that you can use directly. You have to do everything through functions which operate on its internals.

I understand what you mean though. `blob`, `arrayBuffer` etc. have simply not been implemented yet. They're not actually part of the `fetch` specification, so don't really belong here, and as far as I'm aware they've not been implemented anywhere else either. So if you want to use them, you'd have to implement them yourself. And then share them with the rest of us I hope :)

It's not completely clear how an implementation in a separate library would interoperate with bs-fetch, since they have to depend on the same type(s). But if you decide to implement some of it, let me know and I'm sure we can figure something out.

**Comment by phated** [comment]
Ah, that makes sense.  Thanks!
