### ISSUE TITLE
How to send `bytes` value as request body?

### ISSUE THREAD

**Issue by tim2CF** [BuckleTypes/bs-fetch#22]
Hello!
I'm trying to communicate from ReasonML client with server using Google Protocol Buffers.
And I don't know how I can use this library for this purpose :(

```reason
  let encoded_data: bytes = Pbrt.Encoder.to_bytes(encoder);
  let js_array_buffer =  /* what is supposed to be done here??? */

  Fetch.fetchWithInit(
    "https://myapi.com/protobuf",
    Fetch.RequestInit.make(
      ~method_=Post,
      ~body=Fetch.BodyInit.makeWithBufferSource(js_array_buffer),
      ~headers=Fetch.HeadersInit.make({"Content-Type": "application/protobuf"}),
      (),
    ),
  )
  |> Js.Promise.then_(..)
```

The question is - how to get acceptable `js_array_buffer`?

**Comment by glennsl** [comment]
Hey. The type accepted by `makeBufferWithSource` is an abstract type with no functionality associated with it (in this library at least, since it's outside its scope). Essentially it's just a placeholder, but it allows you to create your own bindings to create or retrieve an array buffer by using this type. Or you can use a third-party library to do it, if such a thing exists, and just cast the value to `bufferSource`.

The easiest way to get an array buffer is to bind to [`new ArrayBuffer(length)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer):

    [@bs.new] external : makeArrayBuffer : int => Fetch,bufferSource = "ArrayBuffer";

But them of course you'll probably wanr to fill it with something, so you need to make bindings to do that as well.
