### ISSUE TITLE
Example Post for Form Data

### ISSUE THREAD

**Issue by ridhoassuryadi** [BuckleTypes/bs-fetch#25]
Hi, can you show example's code  for `Post` Form-Data with this library. and then thanks to make this library

**Comment by glennsl** [comment]
Hey. There is no example because there are no form data bindings. There is a PR, #14, which seems stuck in limbo, and there's also been some interest recently in [adding form data bindings to `bs-webapi`](https://github.com/reasonml-community/bs-webapi-incubator/issues/138).

But for now, my advice would be to just borrow the bindings from the PR.
