### ISSUE TITLE
bs-fetch (POST, with url and port)

### ISSUE THREAD

**Issue by DrYSG** [BuckleTypes/bs-fetch#30]
I am trying to modify client program that currently fetches a relative url without port, (POST).

first parameter to the fetchWithInit() is "/graphql"

```
  Bs_fetch.(
    fetchWithInit(
      "/graphql",
      RequestInit.make(
        ~method_=Post,
        ~body=
          Js.Dict.fromList([
            ("query", Js.Json.string(q##query)),
            ("variables", q##variables),
          ])
          |> Js.Json.object_
          |> Js.Json.stringify
          |> BodyInit.make,
        ~credentials=Include,
        ~headers=
          HeadersInit.makeWithArray([|
            ("content-type", "application/json"),
          |]),
        (),
      ),
    )

```

This works but it sends the request to http://localhost/graphql  (which is not where I want the request sent to). The payload body is fine.

```
POST http://localhost:8080/graphql HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Content-Length: 93
Accept: application/json
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
Content-Type: application/json
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:8080/graphql
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,he;q=0.8,yi;q=0.7
Cookie: _ga=GA1.1.342987397.1557346139; com.wibu.cm.webadmin.lang=en-US

{"query":"query {\n  todos {\n    id\n    title\n    completed\n  }\n}\n\n","variables":null}
```

But when I modify this url to be absolute and have a port, I don't have a body anymore, what gives?

```
OPTIONS http://localhost:8080/graphql HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://127.0.0.1:5500
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
Access-Control-Request-Headers: content-type
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Referer: http://127.0.0.1:5500/public/index.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,he;q=0.8,yi;q=0.7

```

here is the modified POST request (the only line that changed was the url.

```
  Bs_fetch.(
    fetchWithInit(
      "http://localhost:8080/graphql",
      RequestInit.make(
        ~method_=Post,
        ~body=
          Js.Dict.fromList([
            ("query", Js.Json.string(q##query)),
            ("variables", q##variables),
          ])
          |> Js.Json.object_
          |> Js.Json.stringify
          |> BodyInit.make,
        ~credentials=Include,
        ~headers=
          HeadersInit.makeWithArray([|
            ("content-type", "application/json")
          |]),
        (),
      ),
    )
```

**Comment by DrYSG** [comment]
BTW, I don't see this as a CORS issue (yet!) since the request is missing the body, and that is before any pre-flight checks are done. (If it is a CORS, I am using, Cohttp_lwt_unix on the server side).

**Comment by glennsl** [comment]
`bs-fetch` is just a very thin layer to translate the standard `fetch` API to BuckleScript. There is very little that can go wrong in this layer, and so far I don't think there has been a single issue with it. That doesn't mean it can't of course, but I think a good approach to troubleshooting these kinds of issues is to try to do the same using `fetch` in pure JavaScript. If that doesn't work either it'll be much easier to find help since a lot more people understand JavaScript code than do ReasonML. And if it does work, it'll be much easier to compare that code to what `bs-fetch` produces to see what's different.

I hope that helps. Let me know how it goes or if you have further questions.

**Comment by DrYSG** [comment]
@glennsl so, you don't see that I am doing anything wrong with my one line change?
I ask since, I am not yet clear on what arguments to fetchWithInit should be. (I will try this with a very thin browser based js fetch also.)

**Comment by glennsl** [comment]
Well, it's not like `bs-fetch` parses the URL, so it really shouldn't make a difference. It just passes it on to `fetch`.

This might well be a misconfiguration, but if so that's likely just because `fetch` is a complex API, and possibly not helped by the translation to `bs-fetch` not being very intuitive. But there's very little transformation done by `bs-fetch` here to make the API significantly different. It translates as directly as possible.

**Comment by DrYSG** [comment]
@glennsl I was just wondering if I should be doing something different for urls with ports, as well as fully qualified URLS. Before I try the replacing the ReasonML code and using JS, I think I will try debugging the compiled bs.js.

**Comment by DrYSG** [comment]
@glennsl  it turns out it is a CORS issue. is there anything that can be done at the client side, Or do you have an example of hacking CoHTTP to added accept-headers ?

```
headers = Cohttp.Header.of_list ["access-control-allow-origin", "*"; (* other headers *)]
```

**Comment by glennsl** [comment]
Good to see you figured it out. I have no experience with  Cohttp, but from what I know about CORS it has to be fixed on server-side. I wouldn't think it should be too hard to add a few headers for a specific request type though.
