### ISSUE TITLE
Would it be possible to have a node "http.request" implementation?

### ISSUE THREAD

**Issue by chrislf** [BuckleTypes/bs-fetch#5]
I have some code which uses fetch, and would like to run automated tests on it. But fetch is a browser technology (c.f  https://github.com/github/fetch/issues/184#issuecomment-126774267) and CLI tests are easiest run via node (AFAIK).

How feasible would it be to have another implementation with the same interface, which uses node's http client underneath?

Thanks for all your work so far!

**Comment by glennsl** [comment]
Hi! I'm not sure why you'd want that, since the comment you link to explains well why doing so would be a bad idea. There'd be subtle semantic differences, so you wouldn't really be able to trust your tests anyway. Additionally, support for node _out of the box_ would at the very least require another layer of indirection, which would significantly increase the amount of code having to be shipped to browsers, adding cost to the primary use case.

But bs-fetch really isn't much more than an interface itself, it doesn't ship with any actual implementation, not even a polyfill, so I think you should be able to just `require('isomorphic-fetch)' to get node support.

Alternatively, as I learned today, there's [bs-axios](https://github.com/meafmira/bs-axios). Though personally I'd just abstract away the low-level IO myself and mock it at a higher level.

I hope this helps, even if it might not be quite what you wanted. I'll go ahead and close this, but feel free to ask any follow-up questions :)

**Comment by chrislf** [comment]
Thank you: isomorphic-fetch does what I need. I'll read up on bs-axios as well, that looks interesting.

Thanks again!
